### ISSUE TITLE
when i train,it takes error

### ISSUE THREAD

**Issue by Yx1322441675** [serend1p1ty/person_search#10]
(Personsearch) goo@goo-Z390-GAMING-X:~/yx/person_search-pytorch/person_search-master$ python tools/train_net.py --gpu 0
[2021-01-11 22:17:52] [train_net.py] [INFO] : Called with args:
Namespace(cfg=None, checkpoint=None, data_dir=None, dataset='psdb_train', epoch=5, gpu=0, rand=False, solver='sgd', tbX=False, weights='/home/goo/yx/person_search-pytorch/person_search-master/data/pretrained_model/resnet50_caffe.pth')
[2021-01-11 22:17:52] [train_net.py] [INFO] : Set to none random mode.
[2021-01-11 22:17:53] [train_net.py] [INFO] : Loaded dataset: psdb_train
[2021-01-11 22:17:53] [train_net.py] [INFO] : Loaded pretrained model from: /home/goo/yx/person_search-pytorch/person_search-master/data/pretrained_model/resnet50_caffe.pth
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "tools/train_net.py", line 181, in <module>
    loss_iter.backward()
  File "/home/goo/anaconda3/envs/Personsearch/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/goo/anaconda3/envs/Personsearch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by serend1p1ty** [comment]
what is your pytorch version

**Comment by Yx1322441675** [comment]
> what is your pytorch version

pip list
Package           Version
----------------- -------------------
certifi           2020.12.5
coloredlogs       15.0
cycler            0.10.0
easydict          1.9
humanfriendly     9.1
kiwisolver        1.3.1
matplotlib        3.3.3
mkl-fft           1.2.0
mkl-random        1.1.1
mkl-service       2.3.0
numpy             1.19.2
olefile           0.46
opencv-python     4.2.0.34
Pillow            8.1.0
pip               20.3.3
pyparsing         2.4.7
python-dateutil   2.8.1
PyYAML            5.3.1
scipy             1.6.0
setuptools        51.0.0.post20201207
six               1.15.0
torch             1.1.0
torchvision       0.3.0
typing-extensions 3.7.4.3
wheel             0.36.2

**Comment by Yx1322441675** [comment]
Can i have your wechat ?

**Comment by serend1p1ty** [comment]
Please discuss it here so as to provide a reference for others.
Can you try
```
import torch
torch.cuda.is_available()
```

**Comment by Yx1322441675** [comment]
> Please discuss it here so as to provide a reference for others.
> Can you try
> 
> ```
> import torch
> torch.cuda.is_available()
> ```

python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False
>>>

**Comment by Yx1322441675** [comment]
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
(base) goo@goo-Z390-GAMING-X:~$ cat /usr/local/cuda-10.1/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

maybe it's the problem that cuda can't match with torch? i need to change the version of cuda?

**Comment by serend1p1ty** [comment]
Your pytorch is not compiled with cuda support or its version is not matched with cuda.
Reinstall pytorch to make ｀torch.cuda.is_available｀ return true

**Comment by Yx1322441675** [comment]
can you tell me the version of your cuda ?

**Comment by serend1p1ty** [comment]
cuda9.2发自我的华为手机-------- 原始邮件 --------发件人： Yx1322441675 <notifications@github.com>日期： 2021年1月12日周二 晚上10:41收件人： serend1p1ty/person_search <person_search@noreply.github.com>抄送： Zj Li <zjli1997@163.com>, Comment <comment@noreply.github.com>主    题： Re: [serend1p1ty/person_search] when i train,it takes error (#10)
can you tell me the version of your cuda ?
