### ISSUE TITLE
which mmdetection version did you use? I did'nt find 55a4023c version mmdeteciton in official repository.

### ISSUE THREAD

**Issue by HenryZhangJianhe** [serend1p1ty/person_search#11]
I did'nt find 55a4023c version of mmdeteciton in official repository.

**Comment by serend1p1ty** [comment]
`git reset --hard 55a4023c`

**Comment by HenryZhangJianhe** [comment]
![image](https://user-images.githubusercontent.com/52202915/109508355-bbf84000-7ada-11eb-932f-b57c1576fc7a.png)
请问这是什么情况，是这么操作吗？

HEAD is now at 55a4023 Fix bug in test time aug (#2858)

**Comment by serend1p1ty** [comment]
Yes, it is now at the right version.
