### ISSUE TITLE
Detector backbone of mmdet-branch is not conv1--layer3_3 which called stem in paper

### ISSUE THREAD

**Issue by HenryZhangJianhe** [serend1p1ty/person_search#12]
![image](https://user-images.githubusercontent.com/52202915/109931608-04df0d00-7d04-11eb-9461-d19263524924.png)
So, it still has good performace using faster-rcnn model with only changing last layer (bbox_head layer add OIM loss)
but reid net is smaller than original model described in paper

**Comment by serend1p1ty** [comment]
The implementation of Faster-RCNN in mmdetection is better than that described in the person search paper.

**Comment by serend1p1ty** [comment]
README.md has been updated about this issue.
