### ISSUE TITLE
RTSP link

### ISSUE THREAD

**Issue by ThanhPham1987** [serend1p1ty/person_search#17]
Hi @serend1p1ty,
How to add the rtsp link into galary to search person?
Best regards,
PeterPham

**Comment by raja1196** [comment]
@serend1p1ty It is a streaming protocol. Most likely @ThanhPham1987 might be looking for real-time solution, on a camera feed maybe?

**Comment by ThanhPham1987** [comment]
Hi @raja1196 
Thanks
Best regards,
peterPham

**Comment by serend1p1ty** [comment]
I am sorry RTSP is beyond the research purpose of the source code. However a PR is welcomed.
You may be interested at the source code of our AAAI 2021 paper [SeqNet-94.8mAP] (https://github.com/serend1p1ty/SeqNet.git).
If you want to implement RTSP, I strongly recommend you to do it upon our SeqNet, which is efficient and powerful.

**Comment by serend1p1ty** [comment]
Feel free to reopen it, if you still have questions.
