### ISSUE TITLE
meaning of 64 in unlabeled_matching_layer

### ISSUE THREAD

**Issue by MasterBin-IIAU** [serend1p1ty/person_search#19]
Hi, thanks for the great work. I am confused about the meaning of 64 in "queue[tail, :64] = features[indx, :64]" 

https://github.com/serend1p1ty/person_search/blob/5116fc6bab20f1adb2d3d959343abaa400b0735e/lib/oim/unlabeled_matching_layer.py#L31

 Could you give some helps? Thanks :)

**Comment by serend1p1ty** [comment]
It was a bug in the official Caffe implementation.
You can refer the issue: https://github.com/ShuangLI59/person_search/issues/128
In fact, I found change 64 to 256 won't bring performance improvement.

**Comment by MasterBin-IIAU** [comment]
Roger that. Thanks for your quick reply :)
