### ISSUE TITLE
How much does detection performance affects the mAP and rank-k metrics?

### ISSUE THREAD

**Issue by HanGuangXin** [serend1p1ty/person_search#24]
Thanks for your awesome work!

As you mentioned, the mAP and Rank-k metric of different Faster-RCNN has a large gap.

origin faster-rcnn: 
mAP: 76.78%, rank-1: 77.48%

mmdetection faster-rcnn:
mAP: 85.21%, rank-1:  85.52%

I was wondering how much does detection performance affects the mAP and rank-k metrics?

looking forward to your reply! @serend1p1ty

**Comment by serend1p1ty** [comment]
We describe how much does detection performance affects the mAP in our paper [SeqNet](https://arxiv.org/abs/2103.10148)
