### ISSUE TITLE
why times 10 for labeled_matching_scores and unlabeled_matching_scores?

### ISSUE THREAD

**Issue by HanGuangXin** [serend1p1ty/person_search#26]
Thanks for your amazing work!
But why we have to times 10 for labeled_matching_scores and unlabeled_matching_scores?
`
            labeled_matching_scores = self.labeled_matching_layer(features, pid_labels)
            labeled_matching_scores *= 10
            unlabeled_matching_scores = self.unlabeled_matching_layer(features, pid_labels)
            unlabeled_matching_scores *= 10
`

**Comment by serend1p1ty** [comment]
@HanGuangXin This is refer to the official implementation.
I guess this is mainly to distinguish between positive and negative samples more clearly.
